### ISSUE TITLE
DEU:SQL17:"Anfügen" is the wrong technical term [id_10603310103_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#497] opened 2017-07-05 18:15 UTC
<p><span style="font-family: 'Arial';font-size: 14px;">&quot;Anh&auml;ngen&quot; is right technical term here</span></p>

**Comment by v-zbing** [comment] 2017-07-14 00:30
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53186

**Comment by Monasr** [comment] 2017-08-03 21:29
Based on the feedback we got from the vendor it seems to be preferential and the issue is resolved by dedign, please let us know you disagree

**Closed by Monasr** 2017-08-03 21:29 UTC
Labels: bug, triaged
